### ISSUE TITLE
When we try to add a private note, app crashes

### ISSUE THREAD

**Issue by imujjwal96** [imujjwal96/Brime#66]
Stack Trace

`10-16 16:04:13.227 1647-1647/com.procleus.brime E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: com.procleus.brime, PID: 1647
                                                                  Theme: themes:{default=overlay:system, iconPack:system, fontPkg:com.frostbit.frio, com.android.systemui=overlay:system, com.android.systemui.navbar=overlay:system}
                                                                  android.os.NetworkOnMainThreadException
                                                                      at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
                                                                      at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:249)
                                                                      at libcore.io.IoBridge.recvfrom(IoBridge.java:549)
                                                                      at java.net.PlainSocketImpl.read(PlainSocketImpl.java:481)
                                                                      at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                      at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                      at com.android.okhttp.okio.Okio$2.read(Okio.java:135)
                                                                      at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                      at com.android.okhttp.okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
                                                                      at com.android.okhttp.internal.http.HttpConnection.isReadable(HttpConnection.java:155)
                                                                      at com.android.okhttp.Connection.isReadable(Connection.java:235)
                                                                      at com.android.okhttp.OkHttpClient$1.isReadable(OkHttpClient.java:91)
                                                                      at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:350)
                                                                      at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
                                                                      at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                      at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
                                                                      at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
                                                                      at com.procleus.brime.CreateNotes$3$1.onClick(CreateNotes.java:156)
                                                                      at android.view.View.performClick(View.java:5204)
                                                                      at android.view.View$PerformClick.run(View.java:21158)
                                                                      at android.os.Handler.handleCallback(Handler.java:739)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by nervehammer** [comment]
fixed app crash 0040ec81a8b829d7adb123d14025110bd11b1476
